### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by reuixiy** [guanqr/blog#1]
我从 Google Analytics 的引荐列表中看到了你的博客，内容非常丰富！感谢你的引荐，也感谢你使用 MemE～

顺便提几点建议：

1. 以 submodule 的方式添加 MemE
这样在更新主题时会方便许多，直接在站点根目录下敲一条命令就行了。同时，上传到 GitHub 上时也会方便些。如果你想要自定义主题的一些模板，直接在站点下新建相应的文件即可覆盖主题的模板，不过这点好像能折腾的你已经摸索出来了哈哈哈。

2. SVG.toml
对于 `data` 文件夹下的文件，无需复制全部内容，Hugo 能按「键」去覆盖文件里的值。如果你要自定义 `brand`，那么只需添加一行即可，只要它的键名为 `brand` 即可。

3. 关闭 `relativeURLs`
如果你不部署到 IPFS 上的话，可以关闭此项，这样在一些页面之间的跳转时，InstantClick 就不会重新刷新页面。

4. 按 sections 分类
你可能会发现分类页面缺失了一级分类，分类的 URL 也没有体现树状分类应有的父子结构。如果你想保持博客的二级分类结构，建议按 sections 分类，这样这两个问题就能解决。为什么会这样呢？这是因为 Hugo 是通过分区（sections）来组织文章的，而不是 Front Matter 中的 `categories`，Hugo 中的 `categories` 其实与 `tags` 没有任何差别，详细说明见最新的 `config.toml` 文件。

5. 使用最新的 `config.toml`
最新版的 `config.toml` 有更好的结构和详细的说明，强烈建议食用。此外，之前我弄错了深色模式的主色，不应该为刺眼的红色的……这点最新版也有修正，如果你想保持现有的，请手动修改 `primaryColorDark` 为 `201, 65%, 62%`。最后，最新版的 `config.toml` 为单语言示例，如果你要配置多语言，建议另在文件的末尾添加，可参考我的博客[该文件的底部](https://github.com/reuixiy/io-oi.me/blob/9dacc09a0aad5a320857795ef396f44d532b8b8d/config.toml#L1111-L1152)。

**Comment by guanqr** [comment]
@reuixiy
感谢您的建议，等我有空再研究研究 ~

**Comment by reuixiy** [comment]
@guanqr 

没事，我这只是看到了就顺便一提，而且就算我不提，这些问题的解决也只是时间的问题，毕竟你也是个很能折腾 + 很求完美的人哈哈哈 :smiley_cat: ~ 还有，咱年纪都差不多，就别「您」了 :joy_cat:...

另外，我刚刚把你的文章全部浏览了一遍，感觉内容很足，也很广。我最近打算在 V2EX 推广一波 MemE，不知是否可以在上面把你的这个博客加入 MemE 的用户列表，这样加上我的两个博客就可以组成数字 3——我最喜欢的奇数 :joy: :)

**Comment by guanqr** [comment]
@reuixiy 

哈哈当然可以啦。

**Comment by reuixiy** [comment]
OK
