### ISSUE TITLE
关于gittalk评论的问题

### ISSUE THREAD

**Issue by linwhitehat** [guanqr/blog#11]
gittalk评论存在的源码泄露问题

**Comment by linwhitehat** [comment]
使用gittalk的话，设置的github应用信息基本源码会显示在网站源码中，我对这个的看法是存在一定问题，但是Gittalkyin应用的管理权限是安全的，所以这个被利用的途径和危害性可能不大，不过还是不想在源码中泄露这种信息，看到你的博客设置的是超链进行issue评论，这部分是在markdown里面设置的吗？

**Comment by guanqr** [comment]
@linwhitehat 你好，我的博客现在使用的是 Hugo + MemE 主题，这项功能是 MemE 主题自带的功能。Hexo 的 NexT 主题目前应该还没有相关的设置。

你可以自己添加一个进行 issue 评论的功能，NexT 主题可以自定义很多内容，参见官方说明：<https://theme-next.org/docs/theme-settings/#Custom-Style-Support>。

![2020-02-04_130740](https://user-images.githubusercontent.com/40543894/73715579-59a20400-474f-11ea-876a-face5eebae5a.png)

比如添加在文章末尾，在对应的文件夹目录下新建 `post-body-end.swig` 文件，直接在该文件中以 HTML 代码格式添加你的 issue 评论的超链接。如果想要美化一下样式，就新建 `styles.styl` 文件，添加 CSS 代码即可。

另外，类似 Gitalk 的第三方评论还有一款叫作 [Utterances](https://github.com/utterance/utterances)。你也可以尝试使用该评论，也是将评论存放于仓库的 issues，但是我觉得比 Gitalk 要好一些，在配置中只需要配置用户和仓库名，不存在泄露源码。不过貌似 NexT 主题目前没有内置该评论功能，需要自己添加相关代码。你可以搜一搜别人如何配置的。

**Comment by linwhitehat** [comment]
> @linwhitehat 你好，我的博客现在使用的是 Hugo + MemE 主题，这项功能是 MemE 主题自带的功能。Hexo 的 NexT 主题目前应该还没有相关的设置。
> 
> 你可以自己添加一个进行 issue 评论的功能，NexT 主题可以自定义很多内容，参见官方说明：https://theme-next.org/docs/theme-settings/#Custom-Style-Support。
> 
> ![2020-02-04_130740](https://user-images.githubusercontent.com/40543894/73715579-59a20400-474f-11ea-876a-face5eebae5a.png)
> 
> 比如添加在文章末尾，在对应的文件夹目录下新建 `post-body-end.swig` 文件，直接在该文件中以 HTML 代码格式添加你的 issue 评论的超链接。如果想要美化一下样式，就新建 `styles.styl` 文件，添加 CSS 代码即可。
> 
> 另外，类似 Gitalk 的第三方评论还有一款叫作 [Utterances](https://github.com/utterance/utterances)。你也可以尝试使用该评论，也是将评论存放于仓库的 issues，但是我觉得比 Gitalk 要好一些，在配置中只需要配置用户和仓库名，不存在泄露源码。不过貌似 NexT 主题目前没有内置该评论功能，需要自己添加相关代码。你可以搜一搜别人如何配置的。

噢噢，了解了，我试试其他的，谢谢

**Comment by linwhitehat** [comment]
感谢，我会多摸索一下hexo和next主题的结构，另外想知道主题深浅色变换这个也是hugo下meme集成的吗，在hexo的next主题中能自定义吗？

**Comment by guanqr** [comment]
@linwhitehat ，试试这个插件：<https://github.com/1v9/hexo-next-nightmode>，需要自己添加 css 样式，比较麻烦。

**Comment by linwhitehat** [comment]
> @linwhitehat ，试试这个插件：https://github.com/1v9/hexo-next-nightmode，需要自己添加 css 样式，比较麻烦。

好，我就刚搭建博客，所以想趁开始接触多折腾一下，也可以对博客搭建和自定义化多了解一点，感谢你的帮助
