### ISSUE TITLE
博客目录文章归类设置

### ISSUE THREAD

**Issue by linwhitehat** [guanqr/blog#15]
你好，我发现我博客的文章按照发布时间存储在对应时间的文件目录下，比如2020/02/10，但是`hexo g`之后在public里面仍然是散放在目录里，没有生成对应时间的文件目录，我设置了new_post_name，请问还有其他地方需要设置吗？

**Comment by guanqr** [comment]
@linwhitehat 根目录博客配置文件 _config.yml 里 `permalink` 是设定文章生成目录的，默认的是：

```
permalink: :year/:month/:day/:title/
```

就是按照年月日进行生成的。参考：<https://hexo.io/zh-cn/docs/configuration#网址>

**Comment by linwhitehat** [comment]
> @linwhitehat 根目录博客配置文件 _config.yml 里 `permalink` 是设定文章生成目录的，默认的是：
> 
> ```
> permalink: :year/:month/:day/:title/
> ```
> 
> 就是按照年月日进行生成的。参考：[https://hexo.io/zh-cn/docs/configuration#网址](https://hexo.io/zh-cn/docs/configuration#%E7%BD%91%E5%9D%80)

嗯嗯，看到了，感谢
