### ISSUE TITLE
关于博客全站https的疑问

### ISSUE THREAD

**Issue by linwhitehat** [guanqr/blog#16]
你好，最近我发现使用GitHub Page部署博客的设置中勾选了强制https，在访问博客网站中各个子站也是https唯独about页面尽管是https访问，但是chrome浏览器会显示“我和网站间的连接并非完全安全”，排除证书、强制https的问题，而且其他子站都没问题，这是什么问题我目前没有头绪，你的站点的子站需要特殊设置吗？能帮忙查看一下吗？

**Comment by linwhitehat** [comment]
问题应该来自谷歌SEO，显示about页面存在重定向，但是响应代码是正常的200，SEO这块的覆盖率问题需要怎么解决好？

**Comment by guanqr** [comment]
你的 about 页面图片用的是一个外链吧，图片链接 http://5b0988e595225.cdn.sohucs.com/images/20190528/dd39a80ee82649aba30f5c61018cc0a2.jpeg ，把图片放在网站里应该就可以了

**Comment by linwhitehat** [comment]
😐原来不能用外链阿，谢谢哈
