### ISSUE TITLE
关于修改字体的问题

### ISSUE THREAD

**Issue by xpye98** [guanqr/blog#26]
同学你好，我按照你这篇文章的介绍修改了字体，为什么字体还显示不出思源字体？
https://guanqr.com/tech/website/web-font-guide/

**Comment by xpye98** [comment]
具体操作，我在_data中添加了自定义的head文件，并且连接到了google font的字体链接，如下

```
<link href="https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@400;500;700&display=swap" rel="stylesheet">
```

next主题中也修改了

```
$font-family-chinese      = "Noto Serif SC";
```

**Comment by guanqr** [comment]
@xpye98 看了看网页源代码，Google Fonts 资源是已经加载了的，只不过在 css 里并没有引用该字体，显示的还是原来的配置。理论上讲添加了 `$font-family-chinese= "Noto Serif SC";` 就已经在全局加载该字体了，问题可能就在  `base.styl` 文件中，试试清除缓存再构建一次。实在不行也可以在 `source/_data/styles.styl` 直接添加字体样式，比如：

```
.post-body {
    font-family: 'Lato', "Noto Serif SC", sans-serif;
}
```

另外在你的网站资源加载中，有部分英文字体加载错误，因为路径不对。我想可能是因为主题配置中字体的这部分，没有配置正确。

**Comment by guanqr** [comment]
如果方便的话可以把主题中修改的代码部分贴上来看一看，包括主题配置文件中的字体配置还有 `base.styl` ~

**Comment by xpye98** [comment]
主题font部分改动如下:
font:
  enable: true
  global:
    external: true
    family: EB Garamond

base.styl如下
// Font families.
$font-family-chinese      = "Noto Serif SC";
$font-family-base         = $font-family-chinese, sans-serif;
$font-family-base         = get_font_family('global'), $font-family-chinese, sans-serif if get_font_family('global');

另外我第一个评论里提到的google字体链接跟你的有所区别（你的那个貌似链接失效了，我在官网找的）

**Comment by xpye98** [comment]
我hexo clean了一下没问题了，多谢！
不过你说的英文字体加载不对，这部分是什么原因呢

**Comment by guanqr** [comment]
刚才建了个新站点试了试，按照上述设置显示的是正常的，我也不知道是哪的问题了

![2020-05-04_221555](https://user-images.githubusercontent.com/40543894/80975623-eb0b3a00-8e54-11ea-9aa2-8b535b250690.png)
![2020-05-04_221608](https://user-images.githubusercontent.com/40543894/80975666-fb231980-8e54-11ea-8e2a-8721265ba2be.png)

![2020-05-04_221620](https://user-images.githubusercontent.com/40543894/80975640-f0688480-8e54-11ea-9190-9becf8ea93c3.png)


![2020-05-04_221159](https://user-images.githubusercontent.com/40543894/80975269-759f6980-8e54-11ea-9813-93d2c605be79.png)

谷歌字体今年三月份更新到了 2.0 版本，原来的链接可能就失效了

**Comment by guanqr** [comment]
刚才建了个新站点试了试，按照上述设置显示的是正常的，我也不知道是哪的问题了

![2020-05-04_221555](https://user-images.githubusercontent.com/40543894/80975623-eb0b3a00-8e54-11ea-9aa2-8b535b250690.png)

![2020-05-04_221608](https://user-images.githubusercontent.com/40543894/80975666-fb231980-8e54-11ea-8e2a-8721265ba2be.png)

![2020-05-04_221620](https://user-images.githubusercontent.com/40543894/80975640-f0688480-8e54-11ea-9190-9becf8ea93c3.png)

![2020-05-04_221159](https://user-images.githubusercontent.com/40543894/80975269-759f6980-8e54-11ea-9813-93d2c605be79.png)

谷歌字体今年三月份更新到了 2.0 版本，原来的链接可能就失效了

**Comment by xpye98** [comment]
嗯嗯，多谢，总之问题解决了
