### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by tianheg** [guanqr/blog#60]
[文章地址](https://github.com/guanqr/blog/blob/master/content/zh/life/ideas/do-not-lose-your-compass.md)

> 有些人对《八佰》中升起了青天白日旗反感，说，「你会为那面青天白日旗挥洒自己的热血吗？」我想说，那是中华民国，我们作为华夏儿女，难道不会为国家的存亡挥洒热学吗？

「热学」-->「热血」

**Comment by guanqr** [comment]
已更正，感谢
