### ISSUE TITLE
博客里可能的typo

### ISSUE THREAD

**Issue by zjjzeng** [guanqr/blog#87]
[找了份普通的工作](https://github.com/guanqr/blog/blob/master/content/zh/life/school/got-a-ordinary-job.md)里准备部分第二段

> 虽然说我没有出去实习过，原本学院安排的实习也因为疫情取消改为了竞赛。但我也不实习经历。

这句话可能写错了~

**Comment by guanqr** [comment]
已更正，谢谢~
